query Bouquet($id: String!) {
  bouquet(id: $id) {
    id
    name
    subname
    price
    description
    code
    image
    personType
    basketStatus @client {
      isInBasket
      basketQuantity
    }
  }
}
